development:
  adapter: postgresql
  encoding: unicode
  database: noclip_development
  pool: 5
  username: postgres
  password: password
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: noclip_test
  pool: 5
  username: postgres
  password: password
  timeout: 5000